@api = http://localhost:3000/tasks  

###
//Get all tasks
GET {{api}}


//Get a task by id
###
GET {{api}}/7

###
//Create a task
POST {{api}}
Content-Type: application/json

{
    "title":"new task",
    "description": "new description"
}

###
//Delete Task by id
DELETE {{api}}/6

//Get tasks total count
###
GET {{api}}/count