@api = http://localhost:3000/api/personal  

###
//Get all tasks
GET {{api}}


//Get a task by id
###
GET {{api}}/10

###
//Create a task
POST {{api}}
Content-Type: application/json

{
    "name": "Agustina",
    "lastName": "Dias",
    "dni": "55433444"
}

### 
// update a task
PUT {{api}}/5
Content-Type: application/json

{
    "name": "Marcela",
    "lastName": "Morello",
    "dni": "66553"
}

###
//Delete Task by id
DELETE {{api}}/4

//Get tasks total count
###
GET {{api}}/count